### ISSUE TITLE
Get rid of "officially curated" and "sign up"

### ISSUE THREAD

**Issue by EmilyKopley** [gkop/bbase#68]
Gabe, As we work to make Birdie better known, I think it's important to make golahny.org look slightly more polished. I know you don't have time to work on this, but I'm just asking for two things: can we get rid of "officially curated" in the "Galleries" section, and can we get rid of "Sign up"? In other words, get rid of the feature that allows people to build their own galleries and us to distinguish between "official" and personal galleries. THANK YOU!!!!

**Comment by gkop** [comment]
No problem, I have made the requested changes, anything else you need sis?

**Comment by EmilyKopley** [comment]
Wonderful! Thanks, bro! Here is a very small thing: can you edit the text about the Brooklyn show so that it is in the past tense ("will present" ==> "presented") and also cut the part that says:

ou can obtain information about the Brooklyn Art & Design Show, and get a 50% discount on a show pass, here:

http://www.neantiqueshows.com/brooklyn.html
***

The URL is : http://www.golahny.org/resources/brooklyn-art-design-show-2015

**Comment by EmilyKopley** [comment]
Also, what about the "sign up" link? can we delete this feature totally, or do we need it so that WE can edit the site?

**Comment by EmilyKopley** [comment]
Btw soon we can add to the "Exhibitions" tab (and the homepage) an announcement about the upcoming show at Lycoming

**Comment by EmilyKopley** [comment]
ALSO: let's add a link to the 2nd annual BG awards. Right now the homepage has a link to the 1st annual. Let's move both of these to...Responses? Ideally we'd have a "News" tab and put both links there, but I'm guessing this is too much work at this point. The link to the 2nd annual BG awards is:

https://ccae.org/golahnyawards

**Comment by gkop** [comment]
I added the link to 2019 awards just now.  I think we can close this, please open a new ticket for loose ends.
