### ISSUE TITLE
Link to exhibition catalogue for Human Abstract, at homepage and Exhibitions page

### ISSUE THREAD

**Issue by EmilyKopley** [gkop/bbase#69]
Gabe, Could you make it so when someone clicks on "The Human Abstract" at the homepage, they download the exhibition catalogue? And could you also create a link to the catalogue at the "Exhibitions" page? I'll email you the catalogue to be sure you have it.

**Comment by gkop** [comment]
The Human Abstract ended so I swapped the announcement for the 2019 Student Awards.

I added an Exhibition for The Human Abstract which links to the catalogue.

I'm open to promoting the catalogue more visibly!! Where else should we link to it?

**Comment by gkop** [comment]
Yay! Thanks Em.
